/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Partials3DDavidHead: typeof import('./src/components/partials/3D/DavidHead.vue')['default']
    PartialsCarouselRotateCarousel: typeof import('./src/components/partials/Carousel/RotateCarousel.vue')['default']
    PartialsDragDragContainer: typeof import('./src/components/partials/Drag/DragContainer.vue')['default']
    PartialsDragDragWindow: typeof import('./src/components/partials/Drag/DragWindow.vue')['default']
    PartialsMusicWidgetMusicSpectrogramm: typeof import('./src/components/partials/MusicWidget/MusicSpectrogramm.vue')['default']
    PartialsNavMenuNavMenu: typeof import('./src/components/partials/NavMenu/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplatesAbout: typeof import('./src/components/templates/About.vue')['default']
    UIAnimatedIconGlitchIcon: typeof import('./src/components/UI/AnimatedIcon/GlitchIcon.vue')['default']
    UIAnimatedIconGlitchText: typeof import('./src/components/UI/AnimatedIcon/GlitchText.vue')['default']
    UIAnimatedTextChangeFontAndImage: typeof import('./src/components/UI/AnimatedText/ChangeFontAndImage.vue')['default']
    UIAnimatedTextChengeRandomLetter: typeof import('./src/components/UI/AnimatedText/ChengeRandomLetter.vue')['default']
    UIAnimatedTextCodeHighlighter: typeof import('./src/components/UI/AnimatedText/CodeHighLighter.vue')['default']
    UIAnimatedTextCodeHighLighter: typeof import('./src/components/UI/AnimatedText/CodeHighLighter.vue')['default']
    UIAnimatedTextGlitchText: typeof import('./src/components/UI/AnimatedText/GlitchText.vue')['default']
  }
}
