/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Partials3DDavidHead: typeof import('./src/components/partials/3D/DavidHead.vue')['default']
    Partials3DOther3d: typeof import('./src/components/partials/3D/other/3d.vue')['default']
    Partials3DOtherCube: typeof import('./src/components/partials/3D/other/cube.vue')['default']
    PartialsSideMenu: typeof import('./src/components/partials/SideMenu/index.vue')['default']
    PartialsSideMenuSideMenu: typeof import('./src/components/partials/SideMenu/SideMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplatesAbout: typeof import('./src/components/templates/About.vue')['default']
    TemplatesAge: typeof import('./src/components/templates/age/index.vue')['default']
    TemplatesAnswer: typeof import('./src/components/templates/answer/index.vue')['default']
    TemplatesQuestion: typeof import('./src/components/templates/question/index.vue')['default']
    TemplatesQuiz: typeof import('./src/components/templates/quiz/index.vue')['default']
    TemplatesResult: typeof import('./src/components/templates/result/index.vue')['default']
    TemplatesSex: typeof import('./src/components/templates/sex/index.vue')['default']
    TemplatesUIInputsCheckbox: typeof import('./src/components/templates/UI/Inputs/Checkbox/index.vue')['default']
    UIAnimatedTextChangeFontAndImage: typeof import('./src/components/UI/AnimatedText/ChangeFontAndImage.vue')['default']
    UIAnimatedTextChengeRandomLetter: typeof import('./src/components/UI/AnimatedText/ChengeRandomLetter.vue')['default']
    UIInputsCheckbox: typeof import('./src/components/UI/Inputs/Checkbox/index.vue')['default']
  }
}
